"""Name mapping between PySB and SimBio."""

name_mapping = {
    "Apaf(bf=1, state='A') % C3(bf=1, state='A')": "Apaf_A_C3_A",
    "Apaf(bf=1, state='A') % C3(bf=1, state='pro')": "Apaf_A_C3_pro",
    "Apaf(bf=1, state='A') % XIAP(bf=1)": "Apaf_A_XIAP",
    "Apaf(bf=1, state='A') % sCas9(sl=2, bf=1) % sCas9(sl=2, bf=None)": "Apaf_A_Sensor_sCas9_dimer",
    "Apaf(bf=1, state='I') % CytoC(bf=1, state='A')": "Apaf_I_CytoC_A",
    "Apaf(bf=None, state='A')": "Apaf.A",
    "Apaf(bf=None, state='I')": "Apaf.I",
    "Apop(bf=1) % C3(bf=1, state='pro')": "Apop_C3_pro",
    "Apop(bf=1) % XIAP(bf=1)": "Apop_XIAP",
    "Apop(bf=1) % sCas9(sl=2, bf=1) % sCas9(sl=2, bf=None)": "Apop_Sensor_sCas9_dimer",
    "Apop(bf=None)": "Apop",
    "BAR(bf=1) % C8(bf=1, state='A')": "BAR_C8_A",
    "BAR(bf=None)": "BAR",
    "Bax(bf=1, s1=2, s2=3, state='A') % Bax(bf=None, s1=4, s2=2, state='A') % Bax(bf=None, s1=5, s2=4, state='A') % Bax(bf=None, s1=3, s2=5, state='A') % Bcl2(bf=1)": "Bax_A4_Bcl2",
    "Bax(bf=1, s1=2, s2=3, state='A') % Bax(bf=None, s1=4, s2=2, state='A') % Bax(bf=None, s1=5, s2=4, state='A') % Bax(bf=None, s1=3, s2=5, state='A') % CytoC(bf=1, state='M')": "Bax_A4_CytoC_M",
    "Bax(bf=1, s1=2, s2=3, state='A') % Bax(bf=None, s1=4, s2=2, state='A') % Bax(bf=None, s1=5, s2=4, state='A') % Bax(bf=None, s1=3, s2=5, state='A') % Smac(bf=1, state='M')": "Bax_A4_Smac_M",
    "Bax(bf=1, s1=2, s2=3, state='M') % Bax(bf=None, s1=4, s2=2, state='M') % Bax(bf=None, s1=5, s2=4, state='M') % Bax(bf=None, s1=3, s2=5, state='M') % Bcl2(bf=1)": "Bax_M4_Bcl2",
    "Bax(bf=1, s1=2, s2=3, state='M') % Bax(bf=None, s1=4, s2=2, state='M') % Bax(bf=None, s1=5, s2=4, state='M') % Bax(bf=None, s1=3, s2=5, state='M') % CytoC(bf=1, state='M')": "Bax_M4_CytoC_M",
    "Bax(bf=1, s1=2, s2=3, state='M') % Bax(bf=None, s1=4, s2=2, state='M') % Bax(bf=None, s1=5, s2=4, state='M') % Bax(bf=None, s1=3, s2=5, state='M') % Mito(bf=1, state='I')": "Bax_M4_Mito_I",
    "Bax(bf=1, s1=2, s2=3, state='M') % Bax(bf=None, s1=4, s2=2, state='M') % Bax(bf=None, s1=5, s2=4, state='M') % Bax(bf=None, s1=3, s2=5, state='M') % Smac(bf=1, state='M')": "Bax_M4_Smac_M",
    "Bax(bf=1, s1=None, s2=2, state='A') % Bax(bf=None, s1=2, s2=None, state='A') % Bcl2(bf=1)": "Bax_A2_Bcl2",
    "Bax(bf=1, s1=None, s2=2, state='M') % Bax(bf=None, s1=2, s2=None, state='M') % Bcl2(bf=1)": "Bax_M2_Bcl2",
    "Bax(bf=1, s1=None, s2=None, state='A') % Bcl2(bf=1)": "Bax_A_Bcl2",
    "Bax(bf=1, s1=None, s2=None, state='A') % CytoC(bf=1, state='M')": "Bax_A_CytoC_M",
    "Bax(bf=1, s1=None, s2=None, state='A') % Smac(bf=1, state='M')": "Bax_A_Smac_M",
    "Bax(bf=1, s1=None, s2=None, state='C') % Bid(bf=1, state='T')": "Bax_C_Bid_T",
    "Bax(bf=1, s1=None, s2=None, state='M') % Bcl2(bf=1)": "Bax_M_Bcl2",
    "Bax(bf=None, s1=1, s2=2, state='A') % Bax(bf=None, s1=3, s2=1, state='A') % Bax(bf=None, s1=4, s2=3, state='A') % Bax(bf=None, s1=2, s2=4, state='A')": "Bax.A4",
    "Bax(bf=None, s1=1, s2=2, state='M') % Bax(bf=None, s1=3, s2=1, state='M') % Bax(bf=None, s1=4, s2=3, state='M') % Bax(bf=None, s1=2, s2=4, state='M')": "Bax.M4",
    "Bax(bf=None, s1=1, s2=None, state='A') % Bax(bf=None, s1=None, s2=1, state='A')": "Bax.A2",
    "Bax(bf=None, s1=1, s2=None, state='M') % Bax(bf=None, s1=None, s2=1, state='M')": "Bax.M2",
    "Bax(bf=None, s1=None, s2=None, state='A')": "Bax.A",
    "Bax(bf=None, s1=None, s2=None, state='C')": "Bax.C",
    "Bax(bf=None, s1=None, s2=None, state='M')": "Bax.M",
    "Bcl2(bf=None)": "Bcl2",
    "Bcl2c(b=1) % Bid(bf=1, state='T')": "Bcl2c_Bid_T",
    "Bcl2c(b=None)": "Bcl2c",
    "Bid(bf=1, state='U') % C8(bf=1, state='A')": "Bid_U_C8_A",
    "Bid(bf=1, state='U') % IntrinsicStimuli(bf=1)": "Bid_U_IntrinsicStimuli",
    "Bid(bf=None, state='T')": "Bid.T",
    "Bid(bf=None, state='U')": "Bid.U",
    "C3(bf=1, state='A') % C6(bf=1, state='pro')": "C3_A_C6_pro",
    "C3(bf=1, state='A') % PARP(bf=1, state='U')": "C3_A_PARP_U",
    "C3(bf=1, state='A') % XIAP(bf=1)": "C3_A_XIAP",
    "C3(bf=1, state='A') % sCas3(sl=2, bf=1) % sCas3(sl=2, bf=None)": "C3_A_Sensor_sCas3_dimer",
    "C3(bf=1, state='pro') % C8(bf=1, state='A')": "C3_pro_C8_A",
    "C3(bf=None, state='A')": "C3.A",
    "C3(bf=None, state='pro')": "C3.pro",
    "C3(bf=None, state='ub')": "C3.ub",
    "C6(bf=1, state='A') % C8(bf=1, state='pro')": "C6_A_C8_pro",
    "C6(bf=None, state='A')": "C6.A",
    "C6(bf=None, state='pro')": "C6.pro",
    "C8(bf=1, state='A') % sCas8(sl=2, bf=1) % sCas8(sl=2, bf=None)": "C8_A_Sensor_sCas8_dimer",
    "C8(bf=1, state='pro') % DISC(bf=1)": "C8_pro_DISC",
    "C8(bf=None, state='A')": "C8.A",
    "C8(bf=None, state='pro')": "C8.pro",
    "C9(bf=None)": "C9",
    "CytoC(bf=1, state='M') % Mito(bf=1, state='A')": "CytoC_M_Mito_A",
    "CytoC(bf=None, state='A')": "CytoC.A",
    "CytoC(bf=None, state='C')": "CytoC.C",
    "CytoC(bf=None, state='M')": "CytoC.M",
    "DISC(bf=1) % flip(bf=1)": "DISC_flip",
    "DISC(bf=None)": "DISC",
    "IntrinsicStimuli(bf=None)": "IntrinsicStimuli",
    "L(bf=1) % R(bf=1)": "L_R",
    "L(bf=None)": "L",
    "Mito(bf=1, state='A') % CytoC(bf=1, state='M')": "CytoC_M_Mito_A",
    "Mito(bf=1, state='A') % Smac(bf=1, state='M')": "Mito_A_Smac_M",
    "Mito(bf=None, state='A')": "Mito.A",
    "Mito(bf=None, state='I')": "Mito.I",
    "PARP(bf=None, state='C')": "PARP.C",
    "PARP(bf=None, state='U')": "PARP.U",
    "R(bf=None)": "R",
    "Smac(bf=1, state='A') % XIAP(bf=1)": "Smac_A_XIAP",
    "Smac(bf=None, state='A')": "Smac.A",
    "Smac(bf=None, state='C')": "Smac.C",
    "Smac(bf=None, state='M')": "Smac.M",
    "XIAP(bf=None)": "XIAP",
    "flip(bf=None)": "flip",
    "sCas3(sl=1, bf=None) % sCas3(sl=1, bf=None)": "Sensor.sCas3_dimer",
    "sCas3(sl=None, bf=None)": "Sensor.sCas3",
    "sCas8(sl=1, bf=None) % sCas8(sl=1, bf=None)": "Sensor.sCas8_dimer",
    "sCas8(sl=None, bf=None)": "Sensor.sCas8",
    "sCas9(sl=1, bf=None) % sCas9(sl=1, bf=None)": "Sensor.sCas9_dimer",
    "sCas9(sl=None, bf=None)": "Sensor.sCas9",
}
